config/routes.rb
Rails.application.routes.draw do
  resources :posts
  root "pages#home"

  get "download", to: 'pages#download'
  get "preview", to: 'pages#preview'
  get 'posts/pdf/:id', to: 'posts#pdf', as: 'post_pdf'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :thumbnail
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home; end

  def download
    pdf = Prawn::Document.new
    pdf.text "Hello"

    send_data(
      pdf.render,
      filename: 'hello.pdf',
      type: 'application.pdf'
    )
  end

  def preview
    pdf = Prawn::Document.new
    pdf.text "This is a preview"
    pdf.text "It's only shows up in the preview route"
    pdf.start_new_page
    pdf.text "This is a new page"

    100.times do |i|
      pdf.text "This is line #{i}"
    end

    send_data(
      pdf.render,
      filename: 'hello.pdf',
      type: 'application.pdf',
      desposition: 'inline'
    )
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy pdf ]

  def index
    @posts = Post.all
  end

  def show; end
  def edit; end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post) }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post) }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
    end
  end

  def pdf
    pdf = Prawn::Document.new
    pdf.text @post.title, size: 20, style: :bold
    pdf.text @post.body

    thumbnail_image = StringIO.open(@post.thumbnail.download)
    pdf.image thumbnail_image, fit: [100, 100]

    send_data(
      pdf.render,
      filename: "#{@post.title}.pdf",
      type: 'application/pdf',
      desposition: 'inline'
    )
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :body, :thumbnail)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">PDF</a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarNav"
      aria-controls="navbarNav"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="<%= posts_path %>">Posts</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= new_post_path %>">Create Post</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PDF</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <header>
      <%= render "layouts/nav" %>
    </header>

    <main class="container py-5">
      <%= yield %>
    </main>
  </body>
</html>

app/views/pages/home.html.erb
<h1 class="display-1">PDF</h1>

<%= link_to "Download", download_path, class: "text-success" %>| |
<%= link_to "Preview", preview_path, class: "text-primary" %>| |
<%= link_to "Posts", posts_path, class: "text-info" %>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div class="my-2">
    <%= form.label :thumbnail, style: "display: block" %>
    <%= form.file_field :thumbnail %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>Title:</strong>
    <%= post.title %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= post.body %>
  </p>

  <%= image_tag(post.thumbnail, style: "width: 200px; height: 200px") %><br>
  <%= link_to "View PDF", post_pdf_path(post), class: "text-dark" %>
</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Posts</h1>

<div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>
    <p>
      <%= link_to "Show this post", post %>
    </p>
  <% end %>
</div>

<%= link_to "New post", new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>

<div>
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", @post, method: :delete %>
</div>